# Generated by Django 4.0.4 on 2022-05-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_goal_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal_cal',
        ),
    ]
