# Generated by Django 4.0.4 on 2022-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PA',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
