# Generated by Django 4.0.4 on 2022-05-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_goal_cal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
