# Generated by Django 4.0.4 on 2022-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(),
        ),
    ]
