# Generated by Django 4.0.4 on 2022-05-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_food_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food_info',
        ),
    ]
