# Generated by Django 4.0.4 on 2022-05-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='food_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_cal', models.IntegerField()),
                ('food_protein', models.FloatField()),
                ('food_fat', models.FloatField()),
                ('food_carbo', models.FloatField()),
                ('food_sugar', models.FloatField()),
                ('food_chole', models.FloatField()),
                ('food_na', models.FloatField()),
                ('food_saturated_fat', models.FloatField()),
                ('food_trans_fat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('food_type', models.IntegerField()),
                ('food_cal', models.IntegerField()),
                ('food_protein', models.FloatField()),
                ('food_fat', models.FloatField()),
                ('food_carbo', models.FloatField()),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='foods.food_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
