# Generated by Django 4.0.4 on 2022-05-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_food',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='user_food',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_food',
            name='food_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='foods.food_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_food',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
